### ISSUE TITLE
Not work when update to latest graphql-server-lambda

### ISSUE THREAD

**Issue by hardyscc** [boazdejong/serverless-graphql-api#2]
```
    "graphql": "^0.10.4",
    "graphql-server-lambda": "^1.0.0",
    "graphql-tools": "^1.1.0"
```

TypeError: Cannot read property 'graphqlLambda' of undefined
at exports.graphql (/var/task/build/handler.js:47:32)

I checked the zip... the export function graphqlLambda is there....  please help... thanks

**Comment by dacz** [comment]
`import { graphqlLambda } from 'graphql-server-lambda'` instead if server and then use directly this named import instead of `server.grapqlLambda(....`.

**Comment by dacz** [comment]
Sorry for typos, replying from phone.

**Comment by hardyscc** [comment]
It is working fine now, thanks a lot :)

**Comment by b04zdotcom** [comment]
This fix has been included, along with the addition of [serverless-webpack](https://github.com/elastic-coders/serverless-webpack) and a different library to merge the schema.
